### ISSUE TITLE
Protobuf mapper unable to map attributes with underscore 

### ISSUE THREAD

**Issue by sahandilshan** [siddhi-io/siddhi-map-protobuf#14]
**Description:**
 protobuf mapper unable to map protobuf attributes with underscore(`string string_value = 1;`)

**Comment by mohanvive** [comment]
@sahandilshan There is a related for this https://github.com/siddhi-io/siddhi-io-grpc/issues/27

**Comment by sahandilshan** [comment]
@mohanvive It's actually an issue of protobuf mapper, not an issue in siddhi-io-grpc
